version: "3.8"
# [Doc] https://danielabaron.me/blog/rails-postgres-docker/#initialization

services:
  database:
    image: postgres:14
    restart: always
    volumes:
      - db_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # Map to something other than default 5432 on host in case Postgres is also running natively on host.
      - "5434:5432"
    environment:
      # Sets the superuser password for PostgreSQL
      POSTGRES_PASSWORD: shhhhItsASecret

  adminer:
    image: adminer
    restart: always
    ports:
    - "8180:8080"
volumes:
  db_pg_data:
